server:
  port: 8080
spring:
  mvc:
    static-path-pattern: /**  
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  devtools:
    restart:
      additional-paths: src/main/java,src/main/resources
      exclude: config/**
  datasource:
    url: jdbc:mysql://localhost:3306/wjq?useUnicode=true&zeroDateTimeBehavior=convertToNull&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
mybatis:
  type-aliases-package: com.wu.spmanager.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  reasonable: true
  support-methods-arguments: true
  helper-dialect: mysql
  params: count=countSql